---
name: Upload OpenAPI specs
on:
  pull_request:
    paths:
      - 'web/api/v1/testdata/openapi_3.*.yaml'
      - '.github/workflows/upload_openapi.yml'
  push:
    branches: [main, 'release-*']
    paths:
      - 'web/api/v1/testdata/openapi_3.*.yaml'
      - '.github/workflows/upload_openapi.yml'
    tags: ['v*']

permissions:
  contents: read

jobs:
  upload_openapi:
    name: Upload OpenAPI specs
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Upload OpenAPI 3.1 spec
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: ./scripts/upload_openapi.sh web/api/v1/testdata/openapi_3.1_golden.yaml "OpenAPI 3.1 Viewer"
      - name: Upload OpenAPI 3.2 spec
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: ./scripts/upload_openapi.sh web/api/v1/testdata/openapi_3.2_golden.yaml "OpenAPI 3.2 Viewer"
